name: fhirlite
description: A lightweight EHR developed in Flutter.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  at_app_flutter: ^5.1.1
  at_client_mobile: ^3.2.9
  at_onboarding_flutter: ^6.0.3
  at_utils: ^3.0.12
  auto_size_text: ^3.0.0
  biometric_storage: ^4.1.3
  cupertino_icons: ^1.0.5
  path_provider: ^2.0.15
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flex_seed_scheme: ^1.3.0
  freezed_annotation: ^2.2.0
  gap: ^3.0.0
  get_it: ^7.6.0
  go_router: ^7.0.1
  google_fonts: ^4.0.4
  hooks_riverpod: ^2.3.6
  intl: ^0.18.0
  json_theme: ^5.0.2
  local_auth: ^2.1.6
  material_design_icons_flutter: ^6.0.7096
  package_info_plus: ^3.1.2
  riverpod_annotation: ^2.1.1
  shared_preferences: ^2.1.1
  url_launcher: ^6.1.11

dev_dependencies:
  build_runner: ^2.4.4
  flutter_lints: ^2.0.1
  flutter_riverpod: ^2.3.6
  freezed: ^2.3.4
  go_router_builder: ^2.0.1
  json_serializable: ^6.7.0
  riverpod_generator: ^2.2.3

dependency_overrides:
    package_info_plus: ^3.1.2

flutter:
  uses-material-design: true
  generate: true
  assets:
  - assets/
  - assets/icons/
  - assets/images/