name: fhirlite
description: A lightweight EHR developed in Flutter.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flex_seed_scheme: ^1.3.0
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  google_fonts: ^4.0.4
  hooks_riverpod: ^2.3.6
  intl: ^0.17.0
  json_theme: ^4.0.3
  package_info_plus: ^4.0.0
  riverpod_annotation: ^2.1.1
  shared_preferences: ^2.1.1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_riverpod: ^2.3.6
  freezed: ^2.3.4
  json_serializable: ^6.6.2
  riverpod_generator: ^2.2.3

flutter:
  uses-material-design: true
  generate: true
  assets:
  - assets/
  - assets/icons/
  - assets/images/