name: fhirlite
description: A lightweight EHR developed in Flutter.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  at_app_flutter: ^5.2.0
  at_client: ^3.0.67
  at_client_mobile: ^3.2.12
  at_fhir:
    path: ../at_fhir
  at_onboarding_flutter: ^6.1.5
  at_utils: ^3.0.15
  biometric_storage: ^5.0.0+4
  cupertino_icons: ^1.0.6
  fhir: ^0.11.4
  fhir_at_rest: ^0.11.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  go_router: ^10.2.0
  hooks_riverpod: ^2.4.5
  intl: ^0.18.1
  json_annotation: ^4.8.1
  local_auth: ^2.1.7
  path_provider: ^2.1.1
  riverpod_annotation: ^2.3.0
  url_launcher: ^6.2.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^3.0.0
  flutter_riverpod: ^2.4.5
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  go_router_builder: ^2.3.4
  json_serializable: ^6.7.1
  mocktail: ^1.0.1
  riverpod_generator: ^2.3.5

flutter:
  uses-material-design: true
  generate: true

dependency_overrides:
  analyzer: ^6.0.0
  intl: ^0.18.1
  uuid: ^4.1.0
