// Flutter imports:
import 'package:flutter/material.dart';

class MayJuunColorScheme extends ColorScheme {
  const MayJuunColorScheme({
    required Brightness brightness,
    required Color primary,
    required Color onPrimary,
    Color? primaryContainer,
    required Color secondary,
    required Color onSecondary,
    Color? secondaryContainer,
    required Color error,
    required Color onError,
    required Color background,
    required Color onBackground,
    required Color surface,
    required Color onSurface,
    this.txtGrey = const Color(0xFF545859),
  }) : super(
          brightness: brightness,
          primary: primary,
          onPrimary: onPrimary,
          primaryContainer: primaryContainer,
          secondary: secondary,
          onSecondary: onSecondary,
          secondaryContainer: secondaryContainer,
          error: error,
          onError: onError,
          background: background,
          onBackground: onBackground,
          surface: surface,
          onSurface: onSurface,
        );

  const MayJuunColorScheme.light({
    Brightness? brightness,
    Color? primary,
    Color? onPrimary,
    Color? primaryContainer,
    Color? secondary,
    Color? onSecondary,
    Color? secondaryContainer,
    Color? error,
    Color? onError,
    Color? background,
    Color? onBackground,
    Color? surface,
    Color? onSurface,
    this.txtGrey = const Color(0xFF545859),
  }) : super.light(
          brightness: brightness ?? Brightness.light,
          primary: primary ?? const Color(0xff6200ee),
          onPrimary: onPrimary ?? Colors.white,
          primaryContainer: primaryContainer,
          secondary: secondary ?? const Color(0xff03dac6),
          onSecondary: onSecondary ?? Colors.black,
          secondaryContainer: secondaryContainer,
          error: error ?? const Color(0xffb00020),
          onError: onError ?? Colors.white,
          background: background ?? Colors.white,
          onBackground: onBackground ?? Colors.black,
          surface: surface ?? Colors.white,
          onSurface: onSurface ?? Colors.black,
        );

  const MayJuunColorScheme.dark({
    Brightness? brightness,
    Color? primary,
    Color? onPrimary,
    Color? primaryContainer,
    Color? secondary,
    Color? onSecondary,
    Color? secondaryContainer,
    Color? error,
    Color? onError,
    Color? background,
    Color? onBackground,
    Color? surface,
    Color? onSurface,
    this.txtGrey = const Color(0xFF545859),
  }) : super.dark(
          brightness: brightness ?? Brightness.dark,
          primary: primary ?? const Color(0xffbb86fc),
          onPrimary: onPrimary ?? Colors.black,
          primaryContainer: primaryContainer,
          secondary: secondary ?? const Color(0xff03dac6),
          onSecondary: onSecondary ?? Colors.black,
          secondaryContainer: secondaryContainer,
          error: error ?? const Color(0xffcf6679),
          onError: onError ?? Colors.black,
          background: background ?? const Color(0xff121212),
          onBackground: onBackground ?? Colors.white,
          surface: surface ?? const Color(0xff121212),
          onSurface: onSurface ?? Colors.white,
        );

  final Color txtGrey;
}
